### ISSUE TITLE
Error on start: Index p_index = 0 is out of bounds

### ISSUE THREAD

**Issue by saletrak** [poohcom1/godot-run-configs#2]
I can't lunch plugin at all. After enabling plugins in Project Settings, editor throws me these errors:
````
scene/main/node.cpp:1529 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
res://addons/run-configs/editor/lib/ui_extension.gd:4 - Cannot call method 'get_child' on a null value.
res://addons/run-configs/editor/lib/ui_extension.gd:13 - Cannot call method 'add_child' on a null value.
scene/main/node.cpp:1529 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
res://addons/run-configs/editor/lib/ui_extension.gd:4 - Cannot call method 'get_child' on a null value.
res://addons/run-configs/editor/lib/ui_extension.gd:13 - Cannot call method 'add_child' on a null value.
scene/main/node.cpp:1529 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
res://addons/run-configs/editor/lib/ui_extension.gd:4 - Cannot call method 'get_child' on a null value.
res://addons/run-configs/editor/lib/ui_extension.gd:13 - Cannot call method 'add_child' on a null value.
````

I'm running this on Godot_4.2.beta5.

**Comment by poohcom1** [comment]
I'm unable to replicate the issue with a blank project on Godot 4.2.beta5. Based on the logs it seems like `EditorInterface.get_base_control()` has no children at the time of plugin start, so it may be related to some caching issue.

Do you have an MRP I can use to test?

**Comment by saletrak** [comment]
Interesting. I've created a new project and bug is still there.
<img width="1800" alt="image" src="https://github.com/poohcom1/godot-run-configs/assets/20685933/40760630-3b53-4269-952e-d5990de3827e">

**Comment by poohcom1** [comment]
Yeah it's quite odd. I've tried the MRP and it's working fine on my machine. Not sure if it could be a Mac-specific issue or if the beta version introduced something weird that only affects certain setup.

----

The error is coming from this function, but all it's doing is just getting the Run Bar node so that it can append the custom buttons.
https://github.com/poohcom1/godot-run-configs/blob/3beb783fb302fe0eb8305a2bbb01c1d092c1169e/addons/run-configs/editor/lib/ui_extension.gd#L3-L9

I've hardcoded the node lookup for performance, but it might be the case that the node hierarchy isn't as static as I expected. I might try to see if there's a more dynamic way to do this that wouldn't break due to different node hierarchies.

**Comment by poohcom1** [comment]
@saletrak  I've made a change that might address this. 

If possible, can you update to the latest version from git to see if it works? You can just copy the contents of [addons/run-configs/editor/lib/ui_extension.gd](https://github.com/poohcom1/godot-run-configs/blob/a873f26f25280d6af24f5ddb403efc4239092a95/addons/run-configs/editor/lib/ui_extension.gd) to your local project since it's the only file that was changed.

**Comment by saletrak** [comment]
It works as intended. Thank you very much for resolving this.
